apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-apps
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/kirillyesikov/fluxCD4vCLuster
  branch: main
